### ISSUE TITLE
pdf에 올라와있는 웹툰들의 미디어 확장을 조사하여 간단히 표로 만들어 봤습니다.

### ISSUE THREAD

**Issue by jaehyeon-s** [chunsejin/web-media-mix#101]
웹소설->웹툰 / 웹툰->드라마 / 웹툰->게임 / 웹툰->굿즈 / 웹툰->무빙툰 / 웹툰->영화
총 6가지 방법으로 조사해봤습니다.

●은 출시가 된 것을 나타내었고,
◐은 출시는 확정되었으나 아직 출시가 되지 않은 것들을 나타냈고,
○은 현재까지 출시도 확정이 되지 않은 것들을 나타내봤습니다.

https://github.com/chunsejin/web-media-mix/blob/jae_branch/pdf%EC%97%90%20%EC%98%AC%EB%9D%BC%EC%99%80%EC%9E%88%EB%8A%94%20%EC%9B%B9%ED%88%B0%EB%93%A4%20%EB%AF%B8%EB%94%94%EC%96%B4%20%ED%99%95%EC%9E%A5%20%EC%A0%95%EB%A6%AC.PNG

**Comment by choibumku00** [comment]
추후 지식 그래프를 확장할때 쓸수 있을것 같습니다. 감사합니다.
