### ISSUE TITLE
arrow.app을 사용해 LPG방식을 이용해 웹툰>게임을 표현

### ISSUE THREAD

**Issue by CountryBird** [chunsejin/web-media-mix#103]
solved #93 

LPG방식을 사용하는 것이 좋을 거라 판단하여, LPG로 표현하여 보았습니다.
수정,보완 후 pull request할 예정이며, 다른 분들에게 빠른 참고자료,가이드라인으로 제안하기 위해 사진 만을 첨부합니다.
다른 분들도 참고하여 제작해 주시면 감사할 것 같습니다.

**<값 없는 버전>**
![미디어믹스(웹툰_게임) 값없음](https://user-images.githubusercontent.com/100738390/163098816-fdb1bd93-b44e-43a6-85fd-11ac40e8a5db.png)  
**<값 있는 버전>**
![미디어믹스(웹툰_게임) 값존재](https://user-images.githubusercontent.com/100738390/163098822-454c705d-9a1d-408b-802c-46257138f2e9.png)

**Comment by VeaNae1** [comment]
수고하셨습니다. 참고해서 반영했습니다.

**Comment by MinkwanK** [comment]
감사합니다.
