### ISSUE TITLE
위키에 LPG와 RDF그래프 비교 사진과 LPG의 장점을 추가했습니다

### ISSUE THREAD

**Issue by dgjinsu** [chunsejin/web-media-mix#104]
LPG 의 개념과 RDF 의 특성들이 나와있지만 한눈에 보기 어려워 RDF 그래프에 비해 LPG 가 갖고 있는 장점과 비교 예시 사진을 추가했습니다.

**Comment by VeaNae1** [comment]
수고하셨습니다. 예시가 생겨서 보기 편해진 것 같습니다

**Comment by choibumku00** [comment]
차이점을 한눈에 알 수 있는 사진인것 같습니다. 감사합니다.
