### ISSUE TITLE
시장용어를 추가했습니다.(OSMU)

### ISSUE THREAD

**Issue by admin9981** [chunsejin/web-media-mix#105]
원소스 멀티유즈 라는 시장용어를 추가했습니다. 추후 코드를 설계할 때 시장의 흐름을 파악하여 설계하는데 도움이 될거라 생각해 추가했습니다.

**Comment by VeaNae1** [comment]
수고하셨습니다.

그런데 현재 Wiki에 용어 정리를 하고 있으니 Wiki로 옮기시는 것은 어떨까요?

**Comment by admin9981** [comment]
현재 LPG관련 정보를 많이 추가하고 있는거 같아 추후에 필요할거같은(프로젝트의 전체적인 내용에 관련) 내용을 따로 올렸었습니다. 위키에 추가해도 괜찮을까요?? @VeaNae1

**Comment by VeaNae1** [comment]
위키를 용어 정리, 설명 등을 모으는 곳으로 사용 중이기 때문에 위키에 추가해도 괜찮을 것이라고 생각합니다.

**Comment by admin9981** [comment]
@VeaNae1 
피드백 감사합니다. 위키에 추가해 놓았습니다. 앞으로 부족하거나 보완해야 할 점이 있으면 이번처럼 좋은 피드백 부탁드립니다!

**Comment by VeaNae1** [comment]
> @VeaNae1 피드백 감사합니다. 위키에 추가해 놓았습니다. 앞으로 부족하거나 보완해야 할 점이 있으면 이번처럼 좋은 피드백 부탁드립니다!

네! 수고하셨습니다!
