### ISSUE TITLE
README.md 파일에 이상한 부분이 있어서 수정하려고 합니다.

### ISSUE THREAD

**Issue by VeaNae1** [chunsejin/web-media-mix#108]
<img width="675" alt="캡처" src="https://user-images.githubusercontent.com/100738731/163120610-975668c1-07d3-49ce-8b7c-b6a47ca3d7c4.PNG">
해당 부분이 이상하게 적용되어있어서 수정하려고 합니다.

해당 부분은 이전에 #94 에서 참고 문헌 간소화가 되었던 부분이기에 삭제하려고 합니다.

동의하시는 분 있으시면 바로 진행하겠습니다.

**Comment by MinkwanK** [comment]
저도 보고 이상하다 생각했습니다.
동의합니다.

**Comment by VeaNae1** [comment]
수정하였습니다.
