### ISSUE TITLE
arrow.app 처음 사용할 때 보시면 도움 될 것 같아서 공유합니다

### ISSUE THREAD

**Issue by dgjinsu** [chunsejin/web-media-mix#109]
https://www.youtube.com/watch?v=ZHJ-BrKJ8A4

**Comment by VeaNae1** [comment]
확실히 처음 사용할 때 많은 도움이 될 것 같습니다. 감사합니다.

**Comment by CountryBird** [comment]
처음 사용하는 사람들에게 큰 도움이 될 것 같네요. 좋은 영상 찾느라 고생하셨습니다.

**Comment by Yoongdi** [comment]
도움이 되었어요 감사합니다!
