### ISSUE TITLE
미디어 믹스의 상품화관련 논문 위키 추가

### ISSUE THREAD

**Issue by admin9981** [chunsejin/web-media-mix#111]
미디어 믹스의 전략에 관한 논문이 올라와 있었지만 기존 시장에서의 동향등이 위주로 나와있는 논문이라 OSMU관련 내용이 추가돼있는 논문을 위키의 OSMU문단에 추가해 놓았습니다. 
추후 프로젝트 개발에 있어 도움이 될거같아 추가하였습니다.

**Comment by choibumku00** [comment]
이 부분에 대해서는 미디어 믹스를 한국에서 원소스멀티유즈 부릅니다.
그래서 따로 분류하는 것보단 '미디어 믹스란'에 포함 시키는게 좋을것같습니다.
그리고 용어 정리기 때문에 Readme에서는 안적어도 될것 같고, wiki에만 적는것이 좋을것 같습니다.

**Comment by admin9981** [comment]
@choibumku00 피드백 감사합니다.
리드미에 있는 정의 지워서 pull requests에 올렸습니다. 앞으로도 좋은 피드백 부탁드립니다!

**Comment by choibumku00** [comment]
그리고 미디어 믹스와 원소스멀티유즈는 같은 단어에 나라마다 다르게 부르는것이어서 wiki에서 조금 수정하겠습니다.
