### ISSUE TITLE
화산귀환 웹소설을 arrow화 해봤습니다

### ISSUE THREAD

**Issue by jinsobak** [chunsejin/web-media-mix#119]
![화산귀환 (웹소설 _ 웹툰)](https://user-images.githubusercontent.com/100740570/163382144-367928e1-3719-406a-9ea3-a632a9caac76.png)

**Comment by choibumku00** [comment]
https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/%EC%82%AC%EB%A1%80/%EC%82%AC%EB%A1%80%20%EC%A0%81%EC%9A%A9%20%EB%AA%A8%EC%9D%8C.md
가능하다면 여기 링크에 들어가서 양식에 맞춰 추가한 뒤 Pull해주시면 감사합니다.
