### ISSUE TITLE
PDF arrows 자료에 웹툰_애니메이션을 추가했습니다.

### ISSUE THREAD

**Issue by SeokJinB** [chunsejin/web-media-mix#121]
![미디어믹스(웹툰_애니메이션)](https://user-images.githubusercontent.com/100738541/163537194-b37e1b95-00f7-46aa-b879-bb352372634c.png)

**Comment by choibumku00** [comment]
arrows에서 share에 전체 공유로 바꿔 주시면 감사합니다.
![image](https://user-images.githubusercontent.com/101037541/163541285-8b45f3ba-67a4-48af-b061-8f122288edc8.png)

**Comment by SeokJinB** [comment]
깜빡했네요 수정했습니다.
