### ISSUE TITLE
웹툰 ost도 미디어 믹스가 맞겠죠?

### ISSUE THREAD

**Issue by jaehyeon-s** [chunsejin/web-media-mix#125]
main branch에 있는 미디어 믹스의 정의를 보게 되면,

"하나의 콘텐츠를 영화, 드라마, 게임, 음반, 굿즈, 장난감, 출판 등의 다양화 방식으로 판매하는 것을 말합니다. 웹툰 원작을 영화로 만든 신과 함께 등이 있습니다. " 라고 나와있습니다. 

엄연히 웹툰 ost도 "음반"에 들어간다고 저는 생각하는데 웹툰을 볼때 ost가 자동으로 틀어지는 데 이걸 판매하는 것이라고 볼 수 있는지 알고 싶습니다.

**Comment by jooonyoung** [comment]
제가 생각하기에도 웹툰 ost역시 미디어 믹스로 간주해도 된다고 봅니다.  다음 웹툰 '취향저격 그녀(작가 로즈옹)'의 오리지널 사운드트랙(ost) 6곡이 음원차트 기준 상위권을 기록한 예시가 있습니다. 웹툰 ost도 현재 음원시장에서 충분한 가치가 있다고 생각하빈다.  해당기사를 참고하였습니다[중앙일보](https://www.joongang.co.kr/article/23872652#home)
