### ISSUE TITLE
영화에서 나왔던 유명한 브금들이 현재까지 사용되는것도 미디어믹스에 해당하나요?

### ISSUE THREAD

**Issue by hxc0102** [chunsejin/web-media-mix#135]
제생각엔 브금에도 저작권이 있어 돈을 받아 판매하여 사용하는 것이니 미디어믹스라고 생각하는데 맞을까요?? 
브금의 예로는 [레옹](https://www.youtube.com/watch?v=XMRqRvcb6hM), [라붐](https://www.youtube.com/watch?v=T5dnEKqOaHw), [미션](https://www.youtube.com/watch?v=V-m5u0OFF_E) 등 다양하게 있습니다.

**Comment by choibumku00** [comment]
네 해당됩니다. 영화에서 끝나는게 아니라 더 확장해서 판매했기에 맞습니다.
