### ISSUE TITLE
Markdown 문법을 정리한 사이트를 찾아봤습니다.

### ISSUE THREAD

**Issue by jy1ee** [chunsejin/web-media-mix#141]
[자주 쓰이는 문법](https://kimmy100b.github.io/markdown/2020/01/07/markdown/)

[기본 구문](https://www.markdownguide.org/basic-syntax/)

[확장 구문](https://www.markdownguide.org/extended-syntax/)

**Comment by sj2305** [comment]
초보자에게 꽤 유용할것 같네요

**Comment by jihoon2819** [comment]
감사합니다

**Comment by madreal3267** [comment]
도움이 될 거 같습니다. 감사합니다.

**Comment by choibumku00** [comment]
감사합니다. 이 내용은 wiki에 추가하는것도 좋을것 같습니다.
