### ISSUE TITLE
카테고리별로 브랜치를 생성하여 자료를 모으면 좋을것같습니다

### ISSUE THREAD

**Issue by pullsss** [chunsejin/web-media-mix#143]
미디어먹스, 지식그래프, 메타데이터 카테고리별 항목에 공용자료들을 올리면 시각적으로 데이터 찾기에 유용할것 같습니다.

**Comment by choibumku00** [comment]
브런치는 새로 추가할 내용이 있을때마다 만드는게 좋을것 같습니다.
브런치를 만들어두면 main에 내용이 추가할때마다 브런치를 만들어야해서 비효율적인것 같습니다.
