### ISSUE TITLE
웹툰 캐릭터를 미디어 믹스를 활용하여 마케팅 한 논문을 찾아보았습니다.

### ISSUE THREAD

**Issue by jooonyoung** [chunsejin/web-media-mix#147]
[미디어믹스- 웹툰 캐릭터를 활용한 마케팅](https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=JAKO201029848353485&dbt=NART)
도움이 되셨으면 좋겠습니다.

**Comment by choibumku00** [comment]
wiki 논문란에 추가했습니다.
