### ISSUE TITLE
웹소설 북검전기 arrows 화 하였습니다.

### ISSUE THREAD

**Issue by madreal3267** [chunsejin/web-media-mix#150]
![북검전기 arrows](https://user-images.githubusercontent.com/55194680/163673088-53306534-ab76-4666-9ede-bc2ae591fa4a.PNG)

**Comment by choibumku00** [comment]
https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/%EC%82%AC%EB%A1%80/%EC%82%AC%EB%A1%80%20%EC%A0%81%EC%9A%A9%20%EB%AA%A8%EC%9D%8C.md
가능하시면 여기 링크에 들어가서 양식에 맞춰 추가해주시면 감사합니다.
