### ISSUE TITLE
트랜스미디어 스토리텔링, 개념화에 대해 작성된 논문을 찾아봤습니다.

### ISSUE THREAD

**Issue by madreal3267** [chunsejin/web-media-mix#151]
스토리텔링에 관하여 알아보던 중 추가로 도움이 될 것 같아서 올립니다.

https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=JAKO201032755115752

**Comment by choibumku00** [comment]
wiki 논문란에 추가했습니다.
