### ISSUE TITLE
해리포터에 적용된 OSMU 전략 사례

### ISSUE THREAD

**Issue by madreal3267** [chunsejin/web-media-mix#152]
WIKI 내 원소스멀티유즈에 참고자료로 올라와있는 논문을 읽던 중 해리포터 내에 적용된 OSMU에 대해 자세하게 알고 싶어서 찾아 보았습니다.

https://smuseum.tistory.com/entry/OSMU-%EC%A0%84%EB%9E%B5-%EC%82%AC%EB%A1%80-%ED%95%B4%EB%A6%AC%ED%8F%AC%ED%84%B0%EC%9D%98-%EB%8B%A4%EC%96%91%ED%95%9C-OSMU-%ED%99%9C%EC%9A%A9%EC%A0%84%EB%9E%B5-%EC%A0%81%EC%9A%A9-%EC%82%AC%EB%A1%80

**Comment by choibumku00** [comment]
wiki의 활용 사례에 추가했습니다.
