### ISSUE TITLE
드라마 '그 해 우리는'도 미디어 믹스가 맞을까요?

### ISSUE THREAD

**Issue by jjeong-yeon** [chunsejin/web-media-mix#161]
'그 해 우리는'은 드라마 방영 동시에 프리퀄 웹툰도 같이 연재를 했습니다. 이것은 드라마가 웹툰화 된 것도 아니고 웹툰이 드라마화 된 것도 아닌데 미디어 믹스가 맞을까요?

**Comment by choibumku00** [comment]
저는 맞다고 생각합니다. 웹툰이나 드라마 하나도 만들수도있었는데 이후 내용을 드라마로 만들어서 동시에 방영했지만
미디어믹스가 한 영역에서 확장하는것이기 때문에 맞다고 생각합니다.
