### ISSUE TITLE
arrow와 neo4j 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by KMJ-KimMinJu** [chunsejin/web-media-mix#163]
arrrow를 하는 것과 neo4j 둘 다 데이터를 시각화 하는 것으로 알고 있는데 둘의 차이점이 있을까요? neo4j를 사용하신 분도 계시고 arrow를 사용하신 분도 계셔서 질문 올립니다.

**Comment by choibumku00** [comment]
arrows는 데이터를 만드는 것이고, neo4j는 데이터베이스인듯합니다.

**Comment by chunsejin** [comment]
Arrow로 만든 데이터를 neo4j로 넣을수 있습니다.
