### ISSUE TITLE
현재 프로젝트의 로드맵을 작성 해보았습니다.

### ISSUE THREAD

**Issue by CountryBird** [chunsejin/web-media-mix#175]
현재, 프로젝트의 명확한 방향성이 없어 많은 사람들이 참여에 어려움이 있을 것 같습니다.
교수님의 Issue #170 를 바탕으로, Roadmap을 작성해 보았으니 많은 분들이 참고해 주시면 감사할 것 같습니다.
혹시 다른 의견이나, 보충할 부분이 있다면 언제든 제안해 주시고,  이견 없을 시 merge하겠습니다.#174

**Comment by choibumku00** [comment]
[로드맵](https://github.com/chunsejin/web-media-mix/blob/Roadmap/Roadmap.md) 한번 봐주시고 의견주시면 감사합니다.
놓친 부분이 많을것 같습니다. 많은 피드백 부탁드립니다.
