### ISSUE TITLE
OSMU와 트랜스미디어에 대한 설명 글을 찾아보았습니다.

### ISSUE THREAD

**Issue by dkekdmf** [chunsejin/web-media-mix#177]
OSMU와 트랜스미디어에 대해 잘 정리된 글 인것 같습니다.  도움이 되었으면 좋겠습니다.
[https://brunch.co.kr/@hwabregas/174](https://brunch.co.kr/@hwabregas/174)

**Comment by MinkwanK** [comment]
감사합니다

**Comment by sj2305** [comment]
감사합니다.
