### ISSUE TITLE
현재까지 한 내용 정리

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#180]
현재 올라온 내용이 많아 한번 정리할겸 올립니다.
최대한 간단하게 적기위해 주요하게 한것만 정리했습니다.
  
1. 미디어 믹스, 메타 데이터, 지식 그래프 용어 정리
> - 미디어 믹스: 웹툰을 포함한 웹 드라마, 웹소설 등 웹에서 일어나는 문화적인 컨텐츠 모두를 일컫는 용어
>  ex) 웹툰에서 영화나 드라마로 진출하는것
> - 메타 데이터: 대량의 정보 가운데에서 찾고 있는 정보를 효율적으로 찾아내서 이용하기 위해 일정한 규칙에 따라 컨텐츠에 대하여 부여되는 데이터이다.
> - 지식 그래프: 개념, 독립체, 관계 및 사건에 대한 상호 연결된 설명의 모음으로 지식모델이다. 
> 구성요소
노드 : 객체 표현 (인물,지역,날짜,문서,그림 등)
엣지 : 노드 간의 연관성/관계 표현 (가족관계, 직업 등)
속성 : 노드, 엣지의 특성들을 설명

2. RDF방식 조사(현재는 사용안합니다.)
> 지식 그래프를 만들기 위한 방식 중 하나입니다. 
> 간단하게 한 노드에 값 하나만 넣을 수 있어서 마인드맵과 비슷합니다.
3. LPG방식 채택
> RDF와 달리 노드에 속성이 있어 여러개의 값이 들어갑니다.
> 원래 RDF방식을 하기로 했으니 난이도 높아 교수님이 LPG방식로 변경했습니다.
>이 부분은 [LPG](https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/PDF%EC%9E%90%EB%A3%8C_arrows.md)여기에서 직접 보고 한번 사용해 보시는게 이해가 잘될 것입니다.
4. arrows 사용 시작
>LPG기반 데이터 구조를 만들때 시각적으로 보면서 만들 수 있어 사용하기 시작했습니다. 
>위에 링크를 들어가서 한번 사용해 보는게 좋습니다. 
5. neo4j
> 아직은 사용하지 않지만 지식 그래프 데이터 베이스로 이용 할 예정입니다.
6. 해야하는것
> 추후 크롤링을 통해 데이터를 들고온다면 데이터가 잘 들어갈 수 있도록 데이터 구조를 만드는 일을 해야합니다.
  
며칠전 로드맵을 올렸었는데 이전 내용도 필요하신 분이 있을까봐 올립니다.

**Comment by Fromis999** [comment]
감사합니다

**Comment by sj2305** [comment]
수고많으셨습니다.

**Comment by Auint** [comment]
수고하셨습니다.
해당 내용을 wiki나 README 혹은 따로 파일을 만들어서 지속적으로 관리해 나가면 좋을 것 같습니다.

**Comment by choibumku00** [comment]
> 수고하셨습니다. 해당 내용을 wiki나 README 혹은 따로 파일을 만들어서 지속적으로 관리해 나가면 좋을 것 같습니다.

감사합니다 기존에 History.md를 만든분이 있어서 거기에 요약본으로 추가하겠습니다.
