### ISSUE TITLE
RDF와 LPG에 개념 (영어)

### ISSUE THREAD

**Issue by Azim9** [chunsejin/web-media-mix#185]
LPG
-> A major variant of graph databases is known as a property graph or labeled property graph (LPG). Property graphs are much simpler than RDF — they consist of a set of nodes and a set of edges, with each node and edge being a essentially a ‘struct’ — a simple data structure consisting of keys and values (which in some cases may themselves be structs). Nowadays JSON is the standard way of encoding these structs — each node and edge is a JSON document, with edges having special keys which indicate that the value represents a pointer to a node.

RDF
-> Whereas RDF uses URLs as identifiers for properties and entities, property graphs use simple strings — purely local identifiers. And while RDF uses the triple as the atom of data, property graphs do not — they are simply collections of arbitrary data-structures, some of which can point at other structures. A third major difference is that RDF is intimately associated with the semantic web. There are many layers that have been built on top to provide descriptions of the semantics of the entities described in RDF graphs. Property graphs, on the other hand, do not attempt to be self-describing at all; the meaning and interpretation of the structures is left up to the consumer of the data. They are just keys and values and, with the exception of edge links and a few other special keys, you can interpret them however you want.

**Comment by Azim9** [comment]
![rdfandlgp](https://user-images.githubusercontent.com/68808693/167332491-f3aa18f7-8a3b-43e5-9277-61b559fa5b06.png)

**Comment by MinkwanK** [comment]
Thank you

**Comment by choibumku00** [comment]
Thank you.
But, the professor said that using the LPG method is better than RDF method.
So we should decide to use the LPG method
