### ISSUE TITLE
지금  우리학교는 Arrow화 해보았습니다.

### ISSUE THREAD

**Issue by dkekdmf** [chunsejin/web-media-mix#186]
![지금우리학교는 Arrow (2)](https://user-images.githubusercontent.com/80977178/167423217-2985704b-9932-4ffc-9666-9d962d6b60fa.png)

**Comment by choibumku00** [comment]
https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/%EC%82%AC%EB%A1%80/%EC%82%AC%EB%A1%80%20%EC%A0%81%EC%9A%A9%20%EB%AA%A8%EC%9D%8C.md
가능하시면 여기 링크에 들어가서 양식에 맞춰 추가해주시면 감사합니다.

**Comment by dkekdmf** [comment]
추가하였습니다 !
