### ISSUE TITLE
History파일을 조금 수정해봤습니다.

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#189]
History에 세세하게 너무 많은 내용이 있어서 필요없는 내용은 삭제하고 핵심 내용만 남겼습니다.
추가적으로 제가 정리한 내용도 좀 추가해서 올렸습니다. 
한번 확인해 주시면 감사합니다. 추가 의견 있으시면 추가하도록 하겠습니다. 
#188

**Comment by VeaNae1** [comment]
처음 History파일을 만들 때 지금까지 작업된 내용들에만 집중하느라 정리를 미쳐 신경쓰지 못했었는데 확실히 깔끔해졌네요! 수고하셨습니다.
