### ISSUE TITLE
Readme 의 참고문헌을 Wiki로 옮기는게 어떤가요?

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#194]
Readme의 참고문헌 단락이 프로젝트 소개에 적절하지 않다고 생각합니다.
따라서, 제 생각엔 Wiki로 옮기는게 더 적절해 보입니다.
Wiki에 국내 참고문헌으로 새로 만들어서 옮기면 괜찮다고 생각합니다.

어떻게 생각하시나요??

**Comment by Auint** [comment]
좋습니다.

다만 README에서 참고내용을 전부 다루지 말고 wiki에 내용들을 기입한 후 중요한 부분만 적어놓는 게 좋아 보입니다.

참고문헌이란 해당 프로젝트에서 주장하는 부분을 뒷받침할 수 있는 부분이라 완전히 빼는 것은 좋지 않을 것 같습니다.

**Comment by MinkwanK** [comment]
> 좋습니다.
> 
> 다만 README에서 참고내용을 전부 다루지 말고 wiki에 내용들을 기입한 후 중요한 부분만 적어놓는 게 좋아 보입니다.
> 
> 참고문헌이란 해당 프로젝트에서 주장하는 부분을 뒷받침할 수 있는 부분이라 완전히 빼는 것은 좋지 않을 것 같습니다.

wiki에 참고내용을 모두 기입한 후에, 그 중에서 중요한 부분을 Readme에서 다루자는 말씀이신가요?

**Comment by choibumku00** [comment]
저도 참고 문헌 내용이 미디어 믹스 전략을 잘 알려주지만 readme에 있을 만큼은 아니라고 봅니다
메타 데이터 내용까지 들어가있는 논문이 있다면 그런 논문을 참고 문헌으로 하면 좋을것 같습니다

**Comment by Auint** [comment]
> > 좋습니다.
> > 다만 README에서 참고내용을 전부 다루지 말고 wiki에 내용들을 기입한 후 중요한 부분만 적어놓는 게 좋아 보입니다.
> > 참고문헌이란 해당 프로젝트에서 주장하는 부분을 뒷받침할 수 있는 부분이라 완전히 빼는 것은 좋지 않을 것 같습니다.
> 
> wiki에 참고내용을 모두 기입한 후에, 그 중에서 중요한 부분을 Readme에서 다루자는 말씀이신가요?

README는 보통 이 프로젝트를 처음 보는 사람이 이 내용을 보고 어떤 부분을 진행하고 있는지 알 수 있게 작성합니다. 따라서 전체적인 맥락을 기입하는 것이 좋고 세부 내용은 wiki부분에 추가를 하는 것이 좋습니다.
참고 문헌 내용에서 어떠한 부분을 참고했다. 라는 부분이 현제 중요한 부분이라면 넣고 아니면 빼도 되겠습니다.

정리하자면
현제로써는 README에 참고문헌이 하나 있지만 이 부분은 wiki에 국내 외 논문 부분과 동일하게 보여서 따로 wiki에 구분 탭을 새로 만들 필요 없이 옮기는 것이 좋겠습니다.
또한 참고 문헌에서 내용 중 중요하게 생각되는 설명이 있다면 README에 추가하시면 되겠습니다.

**Comment by MinkwanK** [comment]
> > > 좋습니다.
> > > 다만 README에서 참고내용을 전부 다루지 말고 wiki에 내용들을 기입한 후 중요한 부분만 적어놓는 게 좋아 보입니다.
> > > 참고문헌이란 해당 프로젝트에서 주장하는 부분을 뒷받침할 수 있는 부분이라 완전히 빼는 것은 좋지 않을 것 같습니다.
> > 
> > 
> > wiki에 참고내용을 모두 기입한 후에, 그 중에서 중요한 부분을 Readme에서 다루자는 말씀이신가요?
> 
> README는 보통 이 프로젝트를 처음 보는 사람이 이 내용을 보고 어떤 부분을 진행하고 있는지 알 수 있게 작성합니다. 따라서 전체적인 맥락을 기입하는 것이 좋고 세부 내용은 wiki부분에 추가를 하는 것이 좋습니다. 참고 문헌 내용에서 어떠한 부분을 참고했다. 라는 부분이 현제 중요한 부분이라면 넣고 아니면 빼도 되겠습니다.
> 
> 정리하자면 현제로써는 README에 참고문헌이 하나 있지만 이 부분은 wiki에 국내 외 논문 부분과 동일하게 보여서 따로 wiki에 구분 탭을 새로 만들 필요 없이 옮기는 것이 좋겠습니다. 또한 참고 문헌에서 내용 중 중요하게 생각되는 설명이 있다면 README에 추가하시면 되겠습니다.

말씀 잘 이해했습니다. 참고문헌 중에서 중요하게 생각되는 부분은 Readme에 실으면 되겠군요. 현재 Readme에 있는 참고문헌은 Wiki로 제가 옮기겠습니다. 감사합니다
