### ISSUE TITLE
이슈와 풀리퀘스트에 올라온 내용중 close할건 하는게 좋을것 같습니다.

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#199]
너무 많은 내용이 올라와서 중요한 내용이 묻힌 글이 많은것 같습니다.
해결한 issues와 닫을 글은 닫는게 좋을것 같습니다.

그래서 이번에 arrows로 사례 적용한것들은 파일하나를 만들어서 모두 모았습니다. #198 
여기에 추가 안된 파일은 링크없이 사진만 올라와있어서 추가 못한겁니다.
merge에 찬성하시면 merge후 arrows관련 이슈는 전부 닫도록 하겠습니다.

추가적으로 arrows이외에도 닫는게 좋다고 생각하시면 의견 수렴후 닫을건 닫도록 하겠습니다.

**Comment by MinkwanK** [comment]
merge에 찬성합니다. arrows 파일들을 하나로 모을 필요가 있었는데 번거로운걸 해주셨네요 고생하셨습니다.

**Comment by sj2305** [comment]
저도 close해도 되는건 빨리 close하는것이 좋다고 생각합니다.

**Comment by choibumku00** [comment]
merge후 close작업 시작하겠습니다.

**Comment by VeaNae1** [comment]
수고하셨습니다. 이렇게 한번 작업해주셨으니 앞으로 완료된 issue는 close하며 중요한 내용이 묻히지 않도록 유지하면 좋을 것이라 생각합니다.
