### ISSUE TITLE
본 과제에 대해 궁금한 부분

### ISSUE THREAD

**Issue by chunsejin** [chunsejin/web-media-mix#20]
궁금한 점이 있다면, 언제든지 문의하시기 바랍니다.

**Comment by MinkwanK** [comment]
안녕하세요 
프로젝트에 관해 이해한 내용이 확실한지 판단이 안돼 질문을 드립니다.
제가 프로젝트를 보고 이해한 내용들입니다.

1. 이 프로젝트가 미디어 믹스에 대한 메타 데이터를 개발하는 프로젝트라고 이해를 했습니다. RDFLib를 사용하여 많은 노드를 정의하면 그만큼 많은 메타 데이터가 쌓이는 것이라고 이해를 했습니다. 
2. 정의한 노드들을 사용하여 그래프를 그린다고 봤습니다. 그래프를 사용하여 정의한 노드들끼리의 관계 및 어떤 연관성을 가지는지를 정의하고 확인하기 쉽게 시각화를 한다고 이해했습니다.

제가 이해한 내용들이 맞나요?
메타 데이터 개발은 처음이라 이해가 빨리 되지 않네요.

좋은 하루 보내십시오 :)

**Comment by chunsejin** [comment]
1. 메타 데이터는 인스턴스(Jane, Tom)보다는 현실/가상세계에 존재하는 개념(사람, 주인공, 히로인)을 중심으로 모델링합니다. 즉, 인스턴스들을 그룹화하는 것이라고 볼수 있습니다.  많은 인스턴스를 담기보다는 인스턴스를 효과 적으로 그룹화할수 있는 개념, 그리고 그들간의 관계 제시하는 것이 중요합니다
2. 맞습니다. 그래프의 개념 모델링을 이해하면 됩니다. Labeled property graph(LPG)에 대한 예제를 찾아보시면 쉽게 이해할수 있습니다

**Comment by MinkwanK** [comment]
답변 감사합니다 
예를 들어 만화 하나를 모델링해도 만화속의 데이터에 대한 그룹화(주인공, 등장인물)를 잘 해야겠군요?

**Comment by chunsejin** [comment]
> 답변 감사합니다 예를 들어 만화 하나를 모델링해도 만화속의 데이터에 대한 그룹화(주인공, 등장인물)를 잘 해야겠군요?

PPT에 그러한 정보에 대해 어느정도 정리했으니 참고하시면 됩니다.

**Comment by MinkwanK** [comment]
감사합니다 ㅎㅎ
잘 이해했습니다
