### ISSUE TITLE
독립일기 arrow화 했습니다.

### ISSUE THREAD

**Issue by jinsobak** [chunsejin/web-media-mix#201]
![독립일기 arrow](https://user-images.githubusercontent.com/100740570/169542480-47f50e18-97b4-4446-8423-9fe9454d623e.png)

**Comment by choibumku00** [comment]
https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/%EC%82%AC%EB%A1%80/%EC%82%AC%EB%A1%80%20%EC%A0%81%EC%9A%A9%20%EB%AA%A8%EC%9D%8C.md
가능하다면 여기 링크에 들어가서 양식에 맞춰 추가한 뒤  Pull해주시면 감사합니다.

**Comment by jinsobak** [comment]
> https://github.com/chunsejin/web-media-mix/blob/main/PDF%EC%9E%90%EB%A3%8C_arrows/%EC%82%AC%EB%A1%80/%EC%82%AC%EB%A1%80%20%EC%A0%81%EC%9A%A9%20%EB%AA%A8%EC%9D%8C.md 가능하다면 여기 링크에 들어가서 양식에 맞춰 추가한 뒤 Pull해주시면 감사합니다.

pull request 했습니다.

**Comment by choibumku00** [comment]
감사합니다. merge했습니다.
