### ISSUE TITLE
Arrow App 공유

### ISSUE THREAD

**Issue by dkekdmf** [chunsejin/web-media-mix#203]
지금 Arrow App 공유가 안되는데 혹시 공유 방법 알고계신분 계실까요?
![share 오류](https://user-images.githubusercontent.com/80977178/169655597-b5d4cf88-09c8-4e46-914c-62863e14ee74.png)
?

**Comment by MinkwanK** [comment]
저도 그런 적이 있어서 해결했었습니다. 지금은 기억이 잘 안나서 정확한지는 잘 모르겠습니다.

구글 계정 -> 데이터 및 개인 정보 보호 -> 내 계정에 액세스 할 수 있는 서드 파티 앱  -> arrows.app 클릭 후 액세스 권한 삭제 
이걸 수행 후, 다시 arrows.app 사이트에 구글 로그인 한 상태로 접속합니다.
구글 드라이브 연동 창이 뜨는데 Authorize를 클릭합니다.

![image](https://user-images.githubusercontent.com/94276637/169655828-a42cd105-829d-4b26-bd22-dd8eb81edb75.png)

빈칸 네모 다 체크 후, 연동해주시면 됩니다. 전 이렇게 하니까 되더라고요.

**Comment by dkekdmf** [comment]
감사합니다. 해결되었습니다
![공유 성공](https://user-images.githubusercontent.com/80977178/169656747-f517692a-fa01-4a46-b24d-c2536ab92bc4.png)
.

**Comment by MinkwanK** [comment]
> 감사합니다. 해결되었습니다 ![공유 성공](https://user-images.githubusercontent.com/80977178/169656747-f517692a-fa01-4a46-b24d-c2536ab92bc4.png) .

다행이네요 고생하셨습니다 ^^
