### ISSUE TITLE
시동 arrow화

### ISSUE THREAD

**Issue by SeokJinB** [chunsejin/web-media-mix#206]
![Webtoon_Movie (1)](https://user-images.githubusercontent.com/100738541/169810572-729c3aee-c2bb-4b22-9647-9ae39005c5f6.png)

arrow 파일 공유링크:https://drive.google.com/file/d/1Yfvbg14Gvt7lU6i9MFzNsGX0yu6o_r1P/view?usp=sharing

**Comment by VeaNae1** [comment]
수고하셨습니다.
#198 에서 현재까지 진행한 arrows 파일들을 한데 모으는 작업을 했으니 해당 경로로 옮기면 좋을 것 같습니다.
