### ISSUE TITLE
Issue 및 Pull request 수행 시 제목과 내용을 자세하게 써주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#208]
**Issue 나 Pull request 작성 시 어떤 목적으로 무슨 내용을 작성했는지 자세하게 써주시면 프로젝트 문서의 가독성이 크게 올라갈 것 같습니다.**  Issue에 여러 도움이 되는 좋은 글들이 많이 올라옵니다. 그러나 제목과 내용에 좀 더 추가적인 설명이 있으면, 읽는데 큰 도움이 될 것 같습니다. 

Pull request 시에는  arrows.app 사례 적용을 한다고 예를 들겠습니다. Pull request  수행 시, "ooo 웹툰에 대한 사례 추가  " 와 같이 어떤 내용의 Pull request 인지 짐작이 가게 **적절한 제목**을 적어주시면 감사하겠습니다. 내용에도 어떤 걸 추가했고 어떤걸 수정했는지 자세하게 적어주시면 프로젝트가 어떻게 흘러가는지 보기가 편할 것 같습니다.

현재 Issue 나 Pull request 작성의 체계 및 양식이 제대로 잡히지 않아, 가독성을 높이기 위해 최소한의 양식이 필요하다고 생각합니다.
의견을 듣고 싶어서 그런데, Comment 부탁드려도 되나요?

**Comment by VeaNae1** [comment]
동의합니다. 적절한 제목과 내용 없이 기재되어 있지 않은 Pull request의 경우 하나하나 열어보며 내용을 파악해야 하는 번거로움이 있었는데, 제목과 내용을 적어준다면 이러한 번거로움이 해결되어 가독성이 향상될 것이라 생각합니다.

**Comment by choibumku00** [comment]
저도 동의합니다. 이슈&풀리퀘스트 템플릿을 만드는것도 좋을것 같습니다.

**Comment by MinkwanK** [comment]
저도 기본적인 템플릿을 만들어두면, 체계성이 갖춰질 것 같습니다. 모두가 동의하는 템플릿이 만들어져야 하기에, 제가 템플릿을 만들어서 여기에 올려보겠습니다. 보시고 피드백 부탁드립니다 ㅎㅎ

**Comment by pshpjr** [comment]
RP 템플릿 제작 중이신가요?

아직 시작하지 않으셨다면 분담해도 괜찮을까요?

**Comment by MinkwanK** [comment]
아니요. 우선 제 깃허브 레포지토리에서 연습삼아 만들어보고 있었습니다. 제가 issue를 맡을테니 Pull Request를 맡으시는게 어떤가요? 그런데 현재 이 레포지토리에서 어떻게 만드는지 모르겠네요...
