### ISSUE TITLE
사례적용들을 종류별로 분류했습니다

### ISSUE THREAD

**Issue by SeokJinB** [chunsejin/web-media-mix#210]
![미디어믹스사례분류](https://user-images.githubusercontent.com/100738541/169956975-5efc3969-f03c-4ce2-ac7a-8cc5ae06d488.PNG)

그림과 같이 웹툰->드라마화의 사례들만 너무 많기 때문에 분류해서 보면 다른 적용사례들도 다양하게 arrow화 할 수 있을 것 같아서 분류를 해보았습니다.

**Comment by choibumku00** [comment]
감사합니다.  더 보기 좋아졌네요

**Comment by jinsobak** [comment]
여러 사례가 한번에 있는 경우에는 어떻게 정리하는게 좋을까요?

**Comment by VeaNae1** [comment]
> 여러 사례가 한번에 있는 경우에는 어떻게 정리하는게 좋을까요?

해당 유형에 모두 포함시키면 어떨까요?
예를 들어 웹툰을 원작으로 웹툰->드라마화, 웹툰->영화화 를 한 작품이 있다면 영화화와 드라마화 두 항목에 모두 포함시키면 좋지 않을까 생각합니다.

**Comment by choibumku00** [comment]
>해당 유형에 모두 포함시키면 어떨까요?
예를 들어 웹툰을 원작으로 웹툰->드라마화, 웹툰->영화화 를 한 작품이 있다면 영화화와 드라마화 두 항목에 모두 포함시키면 좋지 않을까 생각합니다.

저도 이렇게 하는게 좋을 것 같습니다.
