### ISSUE TITLE
5월 29일까지 릴리즈 하나 추가하면 좋을것 같습니다.

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#211]
5월 29일(일)까지 의미있는 활동을 남겨 릴리즈를 하나 추가하면 좋을것 같습니다.
  
제가 생각하고 있는 활동 중 하나는
<details>
<summary>모든 노드 통합</summary>
<div markdown="1"> 
모든 노드 통합 arrows.app 공유(웹툰 -> 웹소설, 드라마, 게임 , 굿즈, 무빙툰, 영화, 애니메이션)
  
https://drive.google.com/file/d/1fXkiz4ji1L3lCajjew7yyiXQdICiTEFk/view?usp=sharing
  
  
![ALL NODE](https://user-images.githubusercontent.com/101037541/168089935-edf871e6-006b-457c-89a7-d1be7bc700a8.png)

  
</div>
</details>
  
이 arrows로 만든 모든 노드 통합 사진을 보고 수정할 부분이 있다면 수정하는게 좋을것 같습니다. 
크롤링후 데이터가 잘 들어갈 수 있도록 노드 속성을 인터넷에서 잘 쓰이는 단어로 정의 할 필요가 있습니다.

예로)  
1. 노드간 엣지(잇는 선)를 정의해주자 <- 이부분은 좀 어려워서 빨간선 정도만 정의 해줄까 저는 생각중입니다.
2. 드라마에 등장인물 칸에 배우 이름도 적자
3. 최상위 노드(웹툰->드라마, 웹소설 등)를 추가하자 (기존에 추가 안되있는 무대화 등등)

이런식으로 의견을 주셔서 최대한 할 수 있는 만큼 수정 후 릴리즈를 하나 추가했으면 합니다.

# 
다른 할만한 활동이나 기여내용을 생각하신게 있다면 커멘드나 이슈를 적성해주세요.
5월 3일 [첫 릴리즈](https://github.com/chunsejin/web-media-mix/releases/tag/v1.0.0) 이후로 활동은 계속 하고 있지만 갱신된 릴리즈가 아직 없어서,
마지막으로 의미있는 변화를 남기고 릴리즈를 갱신하면 좋을것 같습니다.
그리고 29일에 최종적으로 얼마나 변화했는지 확인하고 버전 넘버도 의논해 정했으면 합니다.
의견 내주시는게 제일 중요하지만 할 수 있는 활동이라면 해주시면 감사합니다.

**Comment by choibumku00** [comment]
저는 일단 최상위(웹툰->드라마, 웹소설 등) 노드간 빨간 엣지를 정의하려고 합니다.

**Comment by VeaNae1** [comment]
좋은 생각인 것 같습니다. 예시로 드신 것들 중에 3번을 보고 생각한 것인데 '웹툰-> 연극'을 추가해보는 것은 어떨까요? 찾아보니 '우리 집에 왜 왔니', '찬란하지 않아도 괜찮아' 등 웹툰을 연극화 한 사례가 몇몇 있었습니다.
또한 '웹툰-> 오디오 드라마'를 추가해보는 것도 좋을 것 같습니다. '고래별' 등 웹툰을 오디오드라마화 한 사례가 있었습니다.

**Comment by VeaNae1** [comment]
그리고 현재 모든 노드 통합으로 올려주신 파일에는 웹툰과 다른 미디어와의 관계만 나타나 있는데, '웹소설->오디오 드라마' 등 다른 미디어 간의 관계를 추가해도 좋지않을까 생각합니다.

**Comment by VeaNae1** [comment]
> 좋은 생각인 것 같습니다. 예시로 드신 것들 중에 3번을 보고 생각한 것인데 '웹툰-> 연극'을 추가해보는 것은 어떨까요? 찾아보니 '우리 집에 왜 왔니', '찬란하지 않아도 괜찮아' 등 웹툰을 연극화 한 사례가 몇몇 있었습니다. 또한 '웹툰-> 오디오 드라마'를 추가해보는 것도 좋을 것 같습니다. '고래별' 등 웹툰을 오디오드라마화 한 사례가 있었습니다.

> 그리고 현재 모든 노드 통합으로 올려주신 파일에는 웹툰과 다른 미디어와의 관계만 나타나 있는데, '웹소설->오디오 드라마' 등 다른 미디어 간의 관계를 추가해도 좋지않을까 생각합니다.

이 두 내용에 대한 의견 말해주시면 감사하겠습니다.

**Comment by VeaNae1** [comment]
좋은 생각인 것 같습니다. 예시로 드신 것들 중에 3번을 보고 생각한 것인데 '웹툰-> 연극'을 추가해보는 것은 어떨까요? 찾아보니 '우리 집에 왜 왔니', '찬란하지 않아도 괜찮아' 등 웹툰을 연극화 한 사례가 몇몇 있었습니다.
또한 '웹툰-> 오디오 드라마'를 추가해보는 것도 좋을 것 같습니다. '고래별' 등 웹툰을 오디오드라마화 한 사례가 있었습니다.

그리고 현재 모든 노드 통합으로 올려주신 파일에는 웹툰과 다른 미디어와의 관계만 나타나 있는데, '웹소설->오디오 드라마' 등 다른 미디어 간의 관계를 추가해도 좋지않을까 생각합니다.

위 내용에 대한 의견 말해주시면 감사하겠습니다.

**Comment by MinkwanK** [comment]
인터넷에서 자주 쓰이는 용어를 보고 노드의 Label(속성?)을 수정하면 되겠군요?
3번처럼 아직 저희가 추가할 사례도 많다는 걸 이해했습니다. 할 게 꽤 많아보이는데 파트를 나누기가 좀 어렵겠네요.

**Comment by MinkwanK** [comment]
일본에서의 미디어 믹스 사례를 조사해 봤는데, Vomic이라는 voice와 comic을 합친  만화를 귀로 듣는 컨텐츠도 있었습니다. 저희가 크롤링 하고자 하는 컨텐츠가, 한국 뿐만 아니라 외국의 컨텐츠도 크롤링 하는게 맞다면 제가 이 부분을 작성해보겠습니다.

**Comment by choibumku00** [comment]
>그리고 현재 모든 노드 통합으로 올려주신 파일에는 웹툰과 다른 미디어와의 관계만 나타나 있는데, '웹소설->오디오 드라마' 등 다른 미디어 간의 관계를 추가해도 좋지않을까 생각합니다.  

이 부분은 일단 웹툰만 할 것 같아서 나두는게 좋을것 같습니다. 
그리고 최상위 노드가 자기를 제외한 (n-1)*2개만큼 엣지가 생기기 때문에 복잡해 보일것 같습니다.

>일본에서의 미디어 믹스 사례를 조사해 봤는데, Vomic이라는 voice와 comic을 합친 만화를 귀로 듣는 컨텐츠도 있었습니다. 저희가 크롤링 하고자 하는 컨텐츠가, 한국 뿐만 아니라 외국의 컨텐츠도 크롤링 하는게 맞다면 제가 이 부분을 작성해보겠습니다.

추가할 수 있는 노드가 있다면 일단 추가하면 좋을것 같습니다. 틀이 커지면 커질수록 좋다고 생각합니다.

가능한 부분부터 해주시면 감사합니다!
