### ISSUE TITLE
이후에 arrows파일 수정이 될 경우 따로 파일을 만들어서 관리하는게 어떤가요??

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#214]
현재 [PDF자료_arrows](https://github.com/chunsejin/web-media-mix/tree/main/PDF%EC%9E%90%EB%A3%8C_arrows) 에 계속 갱신하고 있습니다.
그런데 더 이상 PDF파일에 있는 그래프는 다 들고 왔기 때문에 따로 파일을 만들어서 관리하는게 좋을 것 같습니다. 

그래서 방금 data_structre_branch를 만들어서 추가해봤습니다.
[미디어 믹스 데이터 구조.md](https://github.com/chunsejin/web-media-mix/blob/data_structure_branch/%EB%AF%B8%EB%94%94%EC%96%B4%20%EB%AF%B9%EC%8A%A4%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EA%B5%AC%EC%A1%B0.md)
json파일과 cypher는 공유하는 것 보단 링크에 들어가서 받는게 좋을 것 같아서 추가 안했습니다.

저희의 프로젝트 중 가장 중요한게 '미디어 믹스 데이터 구조'라고 생각해서 따로 빼봤는데 의견 남겨주시면 감사합니다.
md파일만 만들지, 폴더로 만들어서 할지 고민하다가 json 파일과 cypher파일을 빼니 폴더가 필요 없을 것 같아서 md파일만 만들었습니다.

**Comment by MinkwanK** [comment]
md 파일로 만드는게 더 가독성이 좋은 것 같습니다. 말씀하신대로 json 파일은 링크로 받을 수 있기 때문입니다.
data_structure_branch는 예시를 보여주기 위해서 만든건가요? 아니면 앞으로 미디어 믹스의 데이터 구조는 쭉 이 branch에 추가하는 것인가요?

**Comment by choibumku00** [comment]
> md 파일로 만드는게 더 가독성이 좋은 것 같습니다. 말씀하신대로 json 파일은 링크로 받을 수 있기 때문입니다.
> 
> data_structure_branch는 예시를 보여주기 위해서 만든건가요? 아니면 앞으로 미디어 믹스의 데이터 구조는 쭉 이 branch에 추가하는 것인가요? 

일단 이렇게 하면 어떨까해서 만들어봤습니다
pdf_arrows폴더는 나두고 이후에 추가되는 내용은 md파일로 따로 관리했으면 합니다
내용 고칠만한점이나 부족한점 없으면 pull하려고합니다

**Comment by VeaNae1** [comment]
> pdf_arrows폴더는 나두고 이후에 추가되는 내용은 md파일로 따로 관리했으면 합니다 

확실히 추가되는 내용을 따로 관리하면 변경된 사항을 알기 쉬워질 것 같습니다.
