### ISSUE TITLE
미디어 믹스 데이터구조 추가

### ISSUE THREAD

**Issue by jy1ee** [chunsejin/web-media-mix#216]
무대화 사례를 찾아서 추가했습니다

(이미지링크를 얻기 위해 이슈를 남겼습니다)
![Untitled graph (3)](https://user-images.githubusercontent.com/90401682/170241707-d3ae06af-6d1e-4b86-8eb1-b5479d65856d.png)

**Comment by choibumku00** [comment]
노드 확장해주셔서 감사합니다!!
혹시 출연진 속성에 값이 들어가 있어서 이 부분만 수정해주실 수 있을까요??
![image](https://user-images.githubusercontent.com/101037541/170418180-fa599714-8fa9-43f3-b217-fa3d87ae778c.png)

그리고 이건 제 생각인데 무대화라는 단어가 좋을지 뮤지컬화가 좋을지 모르겠지만
이왕이면 최상위노드가 뮤지컬로 돼있어서 뮤지컬화가 좋을것 같습니다.
이 부분은 제 생각이라 뭐가 더 좋은지 몰라서 꼭 수정은 안하셔도되고 추후 뭐가 더 좋을지 생각해보고 수정해도 됩니다!!
