### ISSUE TITLE
사례에 게임화를 추가하였습니다

### ISSUE THREAD

**Issue by jinsobak** [chunsejin/web-media-mix#217]
없더군요

**Comment by MinkwanK** [comment]
고생하셨습니다

**Comment by choibumku00** [comment]
혹시 아직 추가 안한건가요?? main에는 안보입니다

**Comment by jinsobak** [comment]
Pullrequest를 merge해주실수 있나요? 거기에 추가되어 있을건데...

2022년 5월 26일 (목) 오후 1:45, choibumku00 ***@***.***>님이 작성:

**Comment by choibumku00** [comment]
아아 네 바로 머지 할게요
