### ISSUE TITLE
arrows.app 기본 그래프 구조 작성에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#219]
https://wikidocs.net/50716

여기서 Neo4j의 그래프 데이터베이스 문서를 보게 됐습니다. 기존의 관계형 데이터베이스와 그래프 데이터베이스의 유사점을 비교한 표를 봤습니다.
![image](https://user-images.githubusercontent.com/94276637/170585377-25d48cd0-36f0-40ab-b00c-b8de09c02fd1.png)

테이블이 Label이고 노드는 행, 속성과 값은 열과 data 라고 합니다. 그렇다면, 저희가 그래프에 넣는 caption은 뭘까?라는 의문점이 들었습니다.
<br><br>
https://wikidocs.net/50747

이슈 209 링크 참고 #209 

이 링크에서 노드는 하나의 개체이며 키-값  쌍으로 구성된 속성과 Label을 가진다고 합니다. Caption에 대한 설명은 안나와있습니다.

제가 유추하기에 arrows.app 에서 노드의 caption은  단지 노드의 간략한 설명이라고 생각합니다.
실제 그래프 데이터베이스에서 그래프 속 노드를 구성하는  데이터는 Property와 property의 값이라고 생각합니다. 

예시로,  제가 생각하는 적절한 그래프를 하나 그렸습니다.

![만화예시 보여주기용](https://user-images.githubusercontent.com/94276637/170586721-99a03d43-7dbf-4830-a7fc-4ae11521fc19.png)

제가 생각하기에, 만화의 제목이 속성과 속성값으로 사진처럼 들어가야 한다고 생각합니다. 현재 그려진 다른 그래프 사례들을 보면 caption에 값을 집어넣은게 보입니다. 제 의견은 caption은 단지 '노드의 간략한 설명일뿐이다' 라는 것입니다. 중요한건, 속성과 속성값이라고 생각합니다.  

저의 추측일 뿐인데, 여러분들의 생각은 어떠한가요?

**Comment by choibumku00** [comment]
와.. 그런것 같습니다. 
https://youtu.be/ZHJ-BrKJ8A4?t=138
이 영상을 보니 caption에 넣엇던 값을 다시 속성으로 넣는데 캡션은 그냥 간단한 설명인것 같습니다. 
좀더 알아본뒤 맞다면 노드 수정을 하도록 하겠습니다.

**Comment by MinkwanK** [comment]
> Reference in

영상을 보니 맞는 것 같네요. 제 생각에, 관계형 데이터베이스와 그래프 데이터베이스의 유사점을 표현한 표를 보는게 중요한 것 같습니다. 그래프 데이터베이스에 노드,레이블,속성등을 넣어보며, 실제로 관계형 데이터베이스에서는 어떻게 구축될지를 상상해보면 되는 것 같습니다.

https://wikidocs.net/50747 
아까 말씀드린대로 여기에서 보니, 관계의 방향성 구현도 중요하게 봐야한다고 생각합니다. 그래서 틀을 제작할때, 관계의 방향도 꽤 생각을 해봐야 하는 것 같습니다. 

제가 작성했던 영화화 그래프는 제가 책임지고 29일안에 수정하도록 하겠습니다. 그리고, 만화책 그래프 및 vomic 그래프의 틀을 만들어보고자 합니다.

**Comment by VeaNae1** [comment]
동의합니다. 말씀하신대로 caption으로 노드에 대한 간략한 설명을 적어주고 해당 노드의 실제값들은 따로 들어가는게 맞는 것 같습니다.
해당 이슈를 본다음 arrows로 작업된 내용들을 살펴봤는데,
[미디어 믹스 데이터 구조.md](https://github.com/chunsejin/web-media-mix/blob/data_structure_branch/%EB%AF%B8%EB%94%94%EC%96%B4%20%EB%AF%B9%EC%8A%A4%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EA%B5%AC%EC%A1%B0.md) 이 곳에 있는 통합 파일은
![image](https://user-images.githubusercontent.com/100738731/170667759-160c6b0c-b94a-4161-91ff-2612e95507b6.png)
사진처럼 대부분 제대로 작업되있다고 생각합니다만, '이름: ' 이나 '제목: ' 속성이 필요한 노드에는 해당 속성을 추가하는 것이 좋겠다고 생각이듭니다. 그리고 해당 파일은 다른 사례에도 적용하기 위한 파일이니 구체적인 값은 빼는 것이 좋아보입니다. 해당부분은 수정한 뒤 Pull requests할테니 추후 확인바랍니다.

구체적인 사례를 작업한 내용들에는 말씀하신 오류가 있는 파일들이 꽤 있었습니다. 해당파일들은 수정이 필요할 것 같습니다.

**Comment by MinkwanK** [comment]
> 동의합니다. 말씀하신대로 caption으로 노드에 대한 간략한 설명을 적어주고 해당 노드의 실제값들은 따로 들어가는게 맞는 것 같습니다.
> 해당 이슈를 본다음 arrows로 작업된 내용들을 살펴봤는데,
> [미디어 믹스 데이터 구조.md](https://github.com/chunsejin/web-media-mix/blob/data_structure_branch/%EB%AF%B8%EB%94%94%EC%96%B4%20%EB%AF%B9%EC%8A%A4%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EA%B5%AC%EC%A1%B0.md) 이 곳에 있는 통합 파일은
> ![image](https://user-images.githubusercontent.com/100738731/170667759-160c6b0c-b94a-4161-91ff-2612e95507b6.png)
> 사진처럼 대부분 제대로 작업되있다고 생각합니다만, '이름: ' 이나 '제목: ' 속성이 필요한 노드에는 해당 속성을 추가하는 것이 좋겠다고 생각이듭니다. 그리고 해당 파일은 다른 사례에도 적용하기 위한 파일이니 구체적인 값은 빼는 것이 좋아보입니다. 해당부분은 수정한 뒤 Pull requests할테니 추후 확인바랍니다.
> 
> 구체적인 사례를 작업한 내용들에는 말씀하신 오류가 있는 파일들이 꽤 있었습니다. 해당파일들은 수정이 필요할 것 같습니다.
> 

미디어믹스 그래프의 틀은 다른 사례에도 공통적으로 적용되어야 하니, 구체적인 속성은 빼자는 말씀인가요? 여러 사례들에 호환되게 그래프의 속성을 간략하게 하자는 말씀으로 이해했습니다 맞나요?

**Comment by VeaNae1** [comment]
> 미디어믹스 그래프의 틀은 다른 사례에도 공통적으로 적용되어야 하니, 구체적인 속성은 빼자는 말씀인가요? 여러 사례들에 호환되게 그래프의 속성을 간략하게 하자는 말씀으로 이해했습니다 맞나요?

네 정확합니다.

**Comment by choibumku00** [comment]
저도 좀 생각해봤는데
![image](https://user-images.githubusercontent.com/101037541/170700961-d563caa9-febd-4851-bad0-0c2384b6e9e2.png)
기존에 키워드 같은 경우에는 사진의 빨간 노드처럼 묶는게 맞지 않을까요??

**Comment by MinkwanK** [comment]
> 저도 좀 생각해봤는데 ![image](https://user-images.githubusercontent.com/101037541/170700961-d563caa9-febd-4851-bad0-0c2384b6e9e2.png) 기존에 키워드 같은 경우에는 사진의 빨간 노드처럼 묶는게 맞지 않을까요??

네 키워드 Label을 만들고 속성을 추가한다면 저렇게 하는게 맞는 것 같습니다!

**Comment by choibumku00** [comment]
일단 보류하고 글작가랑 거의 비슷하게 속성에
키워드: 시대
설명:
로 만들어서 시대에 대한 값을 넣을 수 있도록 만들었습니다 연재나 방영도 똑같이 적용해서 올렸는데 수정할 필요가 있으면 수정하겠습니다

**Comment by MinkwanK** [comment]
> 일단 보류하고 글작가랑 거의 비슷하게 속성에 키워드: 시대 설명: 로 만들어서 시대에 대한 값을 넣을 수 있도록 만들었습니다 연재나 방영도 똑같이 적용해서 올렸는데 수정할 필요가 있으면 수정하겠습니다

올려주시면 제가 보도록 하겠습니다.  글로는 잘 이해가 되지 않아, 실제로 보고 싶네요!

**Comment by choibumku00** [comment]
지금 머지된 상태입니다 main에서 볼수있어요

**Comment by MinkwanK** [comment]
많은 작업 하신다고 정말 고생하셨습니다

![image](https://user-images.githubusercontent.com/94276637/170829800-b0c33ad0-e1a8-42b7-a928-a9b4f38592c1.png)

혹시, 작가 Label 안에 Property로 그림 작가, 각색 작가,글 작가를 넣어 통합시켜도 되지 않을까요? 키워드도 연재도 그런식으로 해도 되지 않을까요?

**Comment by choibumku00** [comment]
솔직히 연재랑 키워드, 방영은 그렇게 하는게 더 맞는것 같습니다.
근데 일단 안바꾼 이유가 예로
작가에서 하나의 노드로 합쳐져 글작가, 그림작가가 다 들어가 있으면
특정 글작가에서 다른 웹툰과 이을 수가 없습니다. 
비슷한 맹략으로 키워드의 시대도 다른 키워드랑 합쳐 하나의 노드로 돼있다면 
조선시대로 예를 들어 이 웹툰의 시대가 조선시대이고 다른 웹툰의 조선시대면 둘이 시대로 이어줄 수가 없습니다.
일단 미디어 믹스라 다른 웹툰과 이어줄 필요는 없어서 하나의 노드로 해도 될 것 같은데 이점까지 고려해서 만들었습니다.
# 
일단 수정한다면
키워드 유형: 시대
설명:

이것을
시대: 
로 바꾸는건 찬성입니다.

노드 하나도 통합하는건 저는 일단 보류한 상태인데,  미디어 믹스라 다른 웹툰과 연결을 안해도 된다는 점에서 변경해도 좋을것 같습니다.

**Comment by MinkwanK** [comment]
다른 웹툰과의 관계를 생각해서 이어줄 걸 생각하니 일부분은 그냥 두는게 맞는 것 같네요. 나중에 하나의 큰 그래프가 된다면 그래프간의 관계 구축에서 choibunku00님의 의견이 더 적절해보입니다. 

키워드유형:시대를 그러면 시대:로 바꿔주 실 수 있나요? 

확실하지 않은건 보류를 하는게 맞는 것 같습니다. 저도 최대한 다음 웹툰과의 연결도 고려하여 만들도록 하겠습니다.

**Comment by choibumku00** [comment]
감사합니다 해당 부분은 내일 수정하도록하겠습니다

**Comment by MinkwanK** [comment]
> 감사합니다 해당 부분은 내일 수정하도록하겠습니다

제가 조금 공부를 하다가 알게 된 내용인데 관계 속성을 이용하면 어떨까요?
![image](https://user-images.githubusercontent.com/94276637/170835179-f0e4f12b-90dd-47e8-8c95-7fc881f2508d.png)

**'관계 속성은 두 노드가 공유하는 정보를 저장한다'** 라고 적혀있더라고요. 두 노드와 공통되는 점이 있다면, 관계를 이용하여 이어주고 거기에 관계 속성을 추가할 수 있더라고요. 저도 아직은 확실하게 잘 모르지만, 이런 방법이 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/94276637/170835234-5afa0c1a-c24d-4a70-abe5-d63aecf5413d.png)

예시입니다.

**Comment by choibumku00** [comment]
일단 A노드에서 B노드로 엣지가 여러개가 될 수 있기 때문에 위에 사진처럼 만들어도 될 것 같습니다.
비슷한 속성 갯수만큼 엣지를 연결하는걸로 하고 위사진처럼 만들겠습니다.

작가의 경우 생각을 해봤는데 작가에서 글작가에 이름만 적을거면 한노드에 글작가,그림작가 다 넣는게 맞고 
글작가의 이름외 정보를 더 넣는다면 글작가 노드, 그림작가 노드 이렇게 나누는게 맞는것 같습니다.
일단 저희는 이름만 하니 다 합쳐서 만들도록하겠습니다.

**Comment by MinkwanK** [comment]
> 일단 A노드에서 B노드로 엣지가 여러개가 될 수 있기 때문에 위에 사진처럼 만들어도 될 것 같습니다. 비슷한 속성 갯수만큼 엣지를 연결하는걸로 하고 위사진처럼 만들겠습니다.
> 
> 작가의 경우 생각을 해봤는데 작가에서 글작가에 이름만 적을거면 한노드에 글작가,그림작가 다 넣는게 맞고 글작가의 이름외 정보를 더 넣는다면 글작가 노드, 그림작가 노드 이렇게 나누는게 맞는것 같습니다. 일단 저희는 이름만 하니 다 합쳐서 만들도록하겠습니다.

네 감사합니다 저도 이름만 하는걸로 이해하고 있습니다.
