### ISSUE TITLE
Issue 템플릿을 추가하였습니다.

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#232]
**기능 추가 의도**<br>
#208 의 Issue에서 작성한 것처럼, 프로젝트의 Issue 작성을 위한 템플릿이 필요하다고 생각했습니다.

**기능 추가 설명**<br>
버그 제보, 기능 추가, 기능 제안, 정보 공유 템플릿을 추가하였습니다.

**추가 설명**<br>
Issue 작성을 클릭하고 원하는 템플릿을 클릭하면 됩니다.
원하시는 템플릿이 없다면, Open a blank issue를 클릭하여 자유롭게 작성하시면 됩니다.
부족한 부분이나 잘못된 부분이 있다면 코멘트 부탁드립니다.

**Comment by choibumku00** [comment]
감사합니다!! 사용해보면서 개선이 필요하면 코멘트 남기겠습니다.

**Comment by pshpjr** [comment]
Wiki Issue 템플릿과 PR 템플릿 추가했습니다.

**Comment by VeaNae1** [comment]
수고많으셨습니다! 체계가 잡혀 Issue의 가독성에 큰 도움이 될 것 같습니다.

**Comment by jy1ee** [comment]
감사합니다 !!
