### ISSUE TITLE
오늘까지 내용으로 릴리즈를 추가하려고 합니다.

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#234]
일단 데이터 구조는 계속 수정을 통해 아직 미흡하지만 틀은 완성됐다고 생각합니다.
그리고 기존 v1.0.0에 비해 History, Roadmap, 이슈/풀리퀘스트 템플릿, 사례 정리, 웹툰 -> 뮤지컬 arrows등등 많은 변화가 있었습니다.
작업하신 내용이 있으면 오늘까지 pull request에 올려주시면 빠르게 판단해서 머지를 하도록 하겠습니다.
릴리즈는 오늘까지 작업이 추가적으로 있을수 있으므로 내일 추가하려고 하는데 버전은 v1.1.0으로 생각하고 있습니다.
버전 의견이나 작업하고 있는 내용이 있어 시간이 필요한 경우 코멘트 남겨주시길 바랍니다.

**Comment by VeaNae1** [comment]
좋은 생각인 것 같습니다. 버전도 적절하다고 생각합니다.

**Comment by choibumku00** [comment]
v1.1.0으로 릴리즈 추가했습니다.

**Comment by VeaNae1** [comment]
> v1.1.0으로 릴리즈 추가했습니다.

수고하셨습니다.

**Comment by MinkwanK** [comment]
고생 많았습니다.

**Comment by choibumku00** [comment]
많은 도움 감사했습니다!!

**Comment by dkekdmf** [comment]
수고하셨습니다.
