### ISSUE TITLE
기존 저장소 Wiki를 중심으로 워드화 해보았는데, PullRequest 해도 될까요?

### ISSUE THREAD

**Issue by dkekdmf** [chunsejin/web-media-mix#241]
**기능 제안이 프로젝트의 문제점과 관련이 있나요?** <br>
워드 파일이 하나 정돈 있어도 된다고 생각합니다.
**기능 제안에 대한 설명** <br>
기존 Wiki를 중심으로 워드화 해보았습니다. 
**추가 설명**<br>
언제 마감될지 몰라 Pull Request 일단 올려놓겠습니다.

**Comment by choibumku00** [comment]
릴리즈 전까지의 wiki내용을 저장할겸 머지 하도록 하겠습니다.

**Comment by dkekdmf** [comment]
감사합니다.
