### ISSUE TITLE
Readme에 단어 설명을 Wiki로 옮기는게 좋을것 같습니다.

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#54]
Readme는 간단하게 구성 하는게 가독성이 좋아 보여 단어 정리는 Wiki에 추가하는것이 좋아보입니다.
그래서 현재 Readme에 있는 단어들은 wiki에 정리 해봤습니다.

**Comment by CountryBird** [comment]
동의합니다.  여러 아이디어들이 많아지다 보면, 불가피하게 Readme가 길어질 것 
같은데 Readme는 취지대로, 간단한 내용 만을 담고 있는 것이 나을 것이라 생각합니다.

**Comment by sj2305** [comment]
Readme에는 진행현황 관련 내용만 추가하고
단어 설명은 wiki에 추가하면 괜찮을 것 같습니다.

**Comment by MinkwanK** [comment]
Wiki 기능이 있는 줄 몰랐는데 알려주셔서 감사합니다

**Comment by chunsejin** [comment]
좋은 아이디어 입니다. Wiki도 조만간에 수업에서 진행할 예정입니다.
