### ISSUE TITLE
프로젝트에 대해 이해한 내용들을 공유했으면 좋겠습니다.

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#60]
현재 web-media-mix 프로젝트에 대해 이해한 내용들을 참여자들끼리 공유 했으면 좋겠습니다. 프로젝트의 방향성에 대해 제대로 이해가 가지 않는 사람이 있을 수도 있다고 생각합니다. 저 또한 제대로 이해가 안되는 부분이 꽤 있고요.

**이슈나 코멘트 또는 slack 을 통해 이해한 정보를 공유하고 서로 모르는 부분에 대하여 질문하면, 학생들 모두 얻어가는게 많을거라고 생각합니다.** 
제 의견에 대해 어떻게 생각하시나요?

**Comment by VeaNae1** [comment]
동의합니다. 서로 정보 공유를 통해 프로젝트에 대한 이해력을 높이면 더 좋은 결과가 있을 것 같습니다.

**Comment by choibumku00** [comment]
저도 같은 생각입니다. 최대한 빨리 많은 사람이 프로젝트를 이해하고 같은 방향으로 나가면 좋을것 같습니다.
가능하면 바로 의견 공유하는게 어떠신가요?

**Comment by MinkwanK** [comment]
제가 생각하는 이번 프로젝트의 최종 목적은 Comicbook ontology를 현재 시점의 미디어와 맞게 metadata vocabulary 를 새로 만드는겁니다. 

rdflib는 이를 이용한 지식 그래프를 형성하는데 사용된다고 이해했습니다. 이 프로젝트는 장기 프로젝트이므로 프로젝트에 필요한 정보들을 모아 정리하는게 중요하다 생각합니다. 그래야 다음 프로젝트 진행자의 프로젝트 진행에 도움을 많이 줄 수 있다고 생각합니다.

제가 이해한 내용이 틀렸을 수도 있고 다른 정보도 얻고 싶기에 다른 분들의 의견도 듣고 싶네요.

**Comment by choibumku00** [comment]
저도 비슷한 생각인것 같습니다. 좀 더 구체적으로 추가하자면 rdflib를 통해 지식 그래프 구조(카테고리?) 샘플을 만드는 것으로 이해했습니다.  
데이터를 구분하기 위해 틀을 짜면 되는것 같습니다.

**Comment by MinkwanK** [comment]
rdflib를 통해 지식 그래프를 작성하기 위한 샘플 틀을 미리 짠다는 것인가요?

**Comment by choibumku00** [comment]
네 맞습니다. 제가 잘못 이해한 것 일수도 있지만
데이터를 저희가 수집하는 것이 아닌것 같기 때문에 샘플 틀만 짜면 된다고 봅니다.

**Comment by MinkwanK** [comment]
Close #60
