### ISSUE TITLE
지식그래프에 대해 공부하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by VeaNae1** [chunsejin/web-media-mix#61]
사용도구를 활용해 모델링하는 과정에서 지식그래프에 대한 지식이 있다면 더 깔끔하고 효율적으로 정리할 수 있을 것 같습니다.
또한 이 프로젝트 의외에 추후에도 계속 도움이 될 것이라 생각하기에 지식그래프에 대해 공부하면 좋겠다고 생각했습니다.

**Comment by MinkwanK** [comment]
지식그래프에 대한 기반지식을 가지고 있으면 RDFLib를 이용하여 모델링할때 확실히 도움이 많이 될 것 같네요.  지식그래프의 노드 및 관계 정의시 uri를 넣는 이유를 잘 모르겠어서 요즘 찾아보고 있습니다.

**Comment by VeaNae1** [comment]
개인적으로 공부 후 정리할 계획입니다. 서로 정리된 지식을 공유하면 아무래도 혼자 공부하는 것보다 도움이 되지 않을까 생각합니다.

**Comment by chunsejin** [comment]
> 지식그래프에 대한 기반지식을 가지고 있으면 RDFLib를 이용하여 모델링할때 확실히 도움이 많이 될 것 같네요. 저도 지식그래프의 노드 및 관계 정의시 uri를 넣는 이유를 잘 모르겠어서 요즘 찾아보고 있습니다.
> 
> 지식그래프에 대해 공부하여 정리한 지식을 깃허브에 올리실려는 생각인가요?

지식그래프의 URI를 넣는 이유는 웹에 존재하는 자원은 URL+URN=URI로 고유하게 식별하고자 합니다. 예제로, https://comicmeta.org/cbo/Agent.html는 코믹메타.org 내에서는 Agent에 대한 개념, 정의과, 다른 개념간의 관계를 표현하게 됩니다.

**Comment by MinkwanK** [comment]
URI에 대해 공부하여 정리를 해봐야겠습니다. 
알려주셔서 감사합니다.
