### ISSUE TITLE
메타데이터를 정의했으면 합니다. 

### ISSUE THREAD

**Issue by pshpjr** [chunsejin/web-media-mix#63]
어떤 작품을 표현할 때 필요한 메타데이터를 정의했으면 합니다.  

도움이 됐으면 해서 pdf에 첨부된 그래프를 보며 필요한 메타데이터들을 정리해 첨부합니다. 

[웹소설-웹툰.txt](https://github.com/chunsejin/web-media-mix/files/8450016/-.txt)

탭으로 노드를 구분했으며, 웹툰이 되면서 추가로 필요하게 된 메타데이터는 + 표시했습니다.

**Comment by MinkwanK** [comment]
메타데이터 정의할때 요긴하겠네요 감사합니다.

**Comment by pullsss** [comment]
틀을 만들때 유용할것 같습니다 감사합니다.
