### ISSUE TITLE
RDF 데이터 시각화 코드입니다. 

### ISSUE THREAD

**Issue by pshpjr** [chunsejin/web-media-mix#68]
https://colab.research.google.com/drive/1eEcO-aH12vf9WP15GPFcYPi1j7M-deAX?usp=sharing

필요한 기능 얘기하시면 추가하겠습니다. 

지금 기능은

1. rdflib에서 정의한 데이터 저장
2. 저장한 데이터 불러오기
3. graphviz를 이용해 데이터 시각화하기 

입니다. 

[MinkwanK](https://github.com/MinkwanK)의 그래프 사용했습니다.

**Comment by MinkwanK** [comment]
저도 RDFLib를 공부하다가 잘 이해가 안되서 그런데 RDF:type이 어떤 노드 타입인지 관계를 말해주는건가요?

**Comment by choibumku00** [comment]
감사합니다. graphviz 사용에 있어서 어느정도 감을 잡을 수 있었습니다.

**Comment by pshpjr** [comment]
LPG를 사용한다면 안 쓸 것 같아 닫습니다.
