### ISSUE TITLE
RDF와 OWL에 대한 짧은 설명입니다.

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#70]
### Triples & URIs

주어(노드) - 동사(엣지) - 목적어(노드)

일반적으로 URI는 주어나 동사에 사용된다. 목적어는 URI이거나 Literal(number, string)로 나타냄.
Literal는 Type을 가질 수 있음. Triple의 장점은 여러 URI 소스들을 구조 변경 없이 하나의 데이터베이스로 가져올 수 있음.

예시: <http://example.com/person/harry> <http://familyontology.net/1.0#hasFather> <http://example.com/person/charles>

### RDF(Resource Descripion Framework) 
웹상의 자원 정보를 표현하기 위한 규격이다. 상이한 메타 데이터간의 효율적인 자원 교환을 가능하게 해준다.
RDF는 triple을 정의하는 방법이다. 'subject' 'predicate' 'object'
rdf:type은 클래스의 인스턴스를 설명하는 속성이다.

ex) :Tolkin :wrote :LordOfTheRings 같은 Linked Graph가 쌓이고 쌓여 방대한 지식 그래프를 구축할 수 있다.

### rdfs(RDF Schema) 
주어 동사 목적어를 대표하는 클래스 또는 관계 정의 가능. OOP 개념과 비슷하다.

### OWL(web ontology language)
무엇을 쓰는지 정의한다 RDF에 비해 더 많은 vocabulary 제공
RDF를 사용하면 오직 목적어만 표현가능하고 RDFS는 클래스를 표현하고,상속을 도와준다. 
하나 하나의 매우 좁은 의미의 Triples를 짤려면 다른 vocabulary가 필요함. OWL이 그런 일을 한다.
사람의 나이에 양수만 들어가게 하는 기능도 수행 가능

RDF -> RDFS -> OWL -> MyWebApp 
표현(구현)되는 순서라고 한다.

자료 출처
https://stackoverflow.com/questions/1740341/what-is-the-difference-between-rdf-and-owl

**제가 자료 조사를 통해 정리한 내용입니다. 부족하지만 도움이 되었으면 좋겠습니다.**

**Comment by VeaNae1** [comment]
정리 감사합니다! 참고하도록 하겠습니다.

**Comment by choibumku00** [comment]
혹시 그러면 rdf/s와 owl은 시각화에 쓰이는 것이 아니라
컴퓨터가 데이터를 이해할 수 있도록 쓰는 언어인건가요??

rdf개념은 진짜 어렵네요..

**Comment by MinkwanK** [comment]
저도 너무 어렵더라고요.... 
rdfs 와 owl을 사용하여 Triples들을 만드는걸로 압니다. 그게 쌓이고 쌓여 지식 그래프를 구축하는 것이라고 전 이해했습니다. 
전 RDF가 있기에 매우 다양한 메타데이터들이 서로 상호 호환되게 정보 교환이 가능하다고 이해했습니다. RDF가 메타데이터의 틀 또는 구조를 잡아주기 때문이라고 생각합니다.

그래프의 시각화에 대한건 저도 자료를 많이 찾아보지 않아 잘 모르겠네요.
그래프의 시각화는 저희가 그래프를 짜고 그걸 시각화하여 제대로 그래프를 형성했는지 확인하기 위함이 아닐까 생각했습니다.
질문을 받으니 공부를 더 열심히 해야겠단걸 느끼네요. 질문해주셔서 감사합니다. 😄

**Comment by chunsejin** [comment]
학부생이 RDF/S와 OWL를 이해하긴 어렵습니다. LPG로 공부하길 추천합니다.

**Comment by choibumku00** [comment]
이 부분을 잘 정리해서 Wiki에 한번 올려보시는건 어떠신가요?
일단 정리해두면 나중에 쓸수도 있을것 같습니다.

**Comment by MinkwanK** [comment]
해보도록 하겠습니다 감사합니다 ㅎㅎ

**Comment by MinkwanK** [comment]
#close 70

**Comment by MinkwanK** [comment]
#close 70
