### ISSUE TITLE
지식그래프에 대해 정리해보았습니다.

### ISSUE THREAD

**Issue by VeaNae1** [chunsejin/web-media-mix#72]
# 지식그래프
개념, 독립체, 관계 및 사건에 대한 상호 연결된 설명의 모음으로 지식모델이다.
설명은 서로 네트워크를 형성하며, 각 독립체는 관련된 독립체의 설명이다.
> [예시](https://www.ontotext.com/wp-content/uploads/2021/06/Plain-KG_KG_KGI-Ok.svg)
## 주요특성
여러 데이터 관리 패러다임의 특성을 결합했다.
* 구조화된 질문들을 통해 데이터를 탐색할 수 있다. -> 데이터베이스
* 이 데이터들이 임의의 다른 네트워크 데이터 구조로 분석될 수 있다. -> 그래프
* 데이터를 해석하고 새로운 사실을 추론하는데 사용될 수 있다. -> 지식 기반
### RDF로 표현되는 지식그래프가 가지는 특성
1. 표현성
* 시맨틱 웹 스택의 표준인 RDF(S) 및 OWL으로 데이터 스키마, 분류 및 어휘, 모든 종류의 메타데이터, 참조 및 마스터 데이터와 같은 다양한 유형의 데이터와 콘텐츠를 유창하게 표현할 수 있도록 한다.
* RDF 확장을 사용하면 출처 및 기타 구조화된 메타데이터를 쉽게 모델링할 수 있다.
2. 성능
* 수십억 개의 정보와 속성의 그래프를 효율적으로 관리 할 수 있도록 모든 사양이 고려되고 실제로 입증되었다.
3. 상호 운용성
* 데이터 직렬화, 액세스(끝점용 SPARQL 프로토콜), 관리(SPARQL 그래프 저장소) 및 페더레이션에 대한 다양한 사양이 존재한다.
* 전역적으로 고유한 식별자를 사용하여 데이터 통합 및 게시하는 것을 용이하게 한다.
4. 표준화
* 위의 모든 내용은 W3C 커뮤니티 프로세스를 통해 표준화되며, 이것으로 다양한 행위자의 요구 사항이 충족되는지 확인한다.
### 온톨로지
지식과 그 사이에 유지되는 관계에 대한 설명이다.
지식 그래프의 공식적 의미이며, 여러가지 표현, 모델링 도구를 가진다.
1. 클래스
* 독립체이다. 객체지향 설계에 의해 사용된다.
> 사물, 위치
* 상위클래스와 하위클래스가 존재한다.
> '위치' 아래의 하위 클래스-> 국가, 도시, 시골 등
2. 관계 유형
* 각 독립체 사이의 관계
> 독립체A------친구관계-------독립체B
3. 카테고리
* 독립체가 속하는 범주
> 책이라는 독립체는 '베스트셀러','어린이책' 등의 범주에 속할 수 있다.
4. 텍스트 설명
* 독립체에 대한 의미, 디자인 의도를 더욱 명확하게 하는 텍스트 설명
* 인간친화적이다.
### 모든 RDF그래프가 지식 그래프는 아니며, 모든 지식기반이 지식 그래프는 아니다.
자료 출처
https://www.ontotext.com/knowledgehub/fundamentals/what-is-a-knowledge-graph/

**여기까지 공부하고 정리해본 내용입니다. 
부족하지만 도움이 되길 바라며 틀린부분이 있다면 지적바랍니다.**

**Comment by MinkwanK** [comment]
W3C가 무슨 특수한 언어 같은건 줄 알았는데 전혀 아니었네요 😐  
정리한다고 고생 많으셨습니다.

**Comment by choibumku00** [comment]
지식 그래프에 대한 많은 내용을 정리 해주셔서 감사합니다. 도움이 됐습니다.

**Comment by seokko** [comment]
감사합니다. 정리한다고 고생많으셨습니다.

**Comment by jy1ee** [comment]
감사합니다 많은 도움이 되었습니다
