### ISSUE TITLE
RDF와 LPG의 차이

### ISSUE THREAD

**Issue by CountryBird** [chunsejin/web-media-mix#74]
"RDFLib은 RDF/S, OWL 등을 위한 지식그래프로 LPG 그래프와는 다르게 작동합니다." 라는 교수님의 말씀에서,
RDF와 LPG의 차이를 궁금해 하는 사람이 있을 것 같아 정리해봅니다.

1) RDF에서는 동일한 노드 간에 같은 유형이 연결될 수 없습니다. 정확히는 식별이 불가능합니다.
2) RDF에서는 관계의 인스턴스를 한정(자격, 속성 등을 의미)할 수 없습니다.
3) RDF는 다중값 속성을, LPG는 배열을 가질 수 있습니다.
4) RDF는 쿼드를 사용하여 명명된 그래프를 정의합니다.

출처 및 참고자료로 링크를 첨부합니다. https://neo4j.com/blog/rdf-triple-store-vs-labeled-property-graph-difference/

**Comment by choibumku00** [comment]
두가지 차이점에 대해서 추가적으로 찾아 봤습니다.
https://joyhong.tistory.com/110

이 사이트에 LPG에서 RDF형태로 변환한걸 보시면 좀더 와닿을것 같습니다.

**Comment by chunsejin** [comment]
두 언어의 제일 큰 차이는 개념 스키마 기반 추론이 가능한 가에 있습니다. 개념 스키마 기반은 학부생 과정이 아니기 때문에, 가능하면 LPG를 사용하는 방향으로 가시길 추천합니다.
