### ISSUE TITLE
PDF파일에 나온 표를 일단 arrow화 해보는게 어떨까요?

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#75]
교수님이 LPG 사용으로 방향을 잡는게 좋을것 같다하셔서 일단 pdf에 있는 그래프들을 arrow화 해보는것도 나쁘지 않을 것 같습니다. 
현재 웹툰 > 소설 (전지적독자시점)은 이미 올린 상태고 그다음 웹툰>드라마 (경이로운 소문)을 제가 만들고 있습니다.
혹시 도와주실분 댓글에 말씀해주시면 파트 나눠서 하면 좋을것같습니다.

**Comment by CountryBird** [comment]
좋은 생각이라 생각합니다. 그럼 제가 웹툰>게임(전자오락수호대)를 만들어보겠습니다.

**Comment by lsm2000** [comment]
저도 동의합니다. 제가 웹툰>굿즈(이런영웅은싫어)를 만들어보고싶습니다.

**Comment by MinkwanK** [comment]
저는 웹툰>영화(신과함께) 를 해보겠습니다.

**Comment by choibumku00** [comment]
arrows_branch를 새로 만들어놨습니다 
가능하시면 양식을 비슷하게 해서 올려주시면 감사합니다

**Comment by MinkwanK** [comment]
양식은 PDF 파일의 양식과 최대한 같게 하면 되나요?

**Comment by choibumku00** [comment]
상세 값은 안 넣고 만들었습니다
arrows.app에서 caption에만 값넣고 labels, properties는 값을 안 넣었습니다.

https://github.com/chunsejin/web-media-mix/blob/arrows_branch/PDF%EC%9E%90%EB%A3%8C_arrows/PDF%EC%9E%90%EB%A3%8C_arrows.md

여기에 이미 4개가 올라가 있어서 한번 보시고 만들어주시면 감사합니다.

**Comment by MinkwanK** [comment]
미리 양식 만들어 두셨네요 감사합니다 ㅎㅎ

**Comment by minche0l** [comment]
웹소설 - 웹툰에서 등장인물에서 시작되는 부분에 등장인물의 이름을 제거해도 된다고 생각합니다 왜냐하면 등장인물의 이름에서 뻗어나가는 것들이 등장인물의 이름에 포함되는 것이 아닌  등장인물에 포함되는 것이라고 생각하기 때문입니다 성별이나 나이가 등장인물의 이름과는 관련이 없다고 생각합니다

**Comment by choibumku00** [comment]
> 관련 파일에 오타가 있어 알려드립니다. "caption": "웝툰", 부분이 웝툰으로 되어있습니다.

감사합니다. 방금 수정 했습니다. 사진과 json파일은 금방 고쳐서 다시 업로드 하겠습니다.
웹툰 - 드라마도 권한 닫혀있는줄 몰랐는데 방금 열었습니다.

**Comment by choibumku00** [comment]
> 웹소설 - 웹툰에서 등장인물에서 시작되는 부분에 등장인물의 이름을 제거해도 된다고 생각합니다 왜냐하면 등장인물의 이름에서 뻗어나가는 것들이 등장인물의 이름에 포함되는 것이 아닌 등장인물에 포함되는 것이라고 생각하기 때문입니다 성별이나 나이가 등장인물의 이름과는 관련이 없다고 생각합니다

저도 만드는 중 그렇게 생각했는데 일단 pdf파일에는 그렇게 만들어져 있어서  이렇게 만들었었습니다. 근데 그 방향이 맞는것 같아서 그렇게 수정하도록 하겠습니다.
