### ISSUE TITLE
Slack에서 서로 소통을 하는게 어떨까요?

### ISSUE THREAD

**Issue by MinkwanK** [chunsejin/web-media-mix#77]
slack의 web-media-mix 채널에서 서로 질문을 하거나 토의를 하면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by sj2305** [comment]
좋은 생각입니다.

**Comment by Fromis999** [comment]
저도 좋다고 생각 합니다.

**Comment by hxc0102** [comment]
원활한 소통이 될 것 같습니다.
채널위치를 모르시는 분들이 있을 수 있어 적어봅니다.
slack에 들어가서 검색 -> 채널탐색 눌러보시면 관련된 프로젝트 각 채널이 있으니 참여를 하시면 됩니다.
