### ISSUE TITLE
Wiki의 맨 윗줄 부분은 없어도 될 것 같습니다.

### ISSUE THREAD

**Issue by sj2305** [chunsejin/web-media-mix#80]
자세히 알아본 결과, 각종 위키(나무위키, 위키피디아 등)의 초반 부분엔 해당 주제에 대한 전반적인 개요가 
가장 먼저 나오는것이 일반적인데

'Welcome to the web-media-mix wiki!' 
이 인사말 부분까진 굳이 있어야 될 필요가 없다고 판단됩니다.

여러분들은 어떻게 생각하시나요?

**Comment by Fromis999** [comment]
저도 동의합니다

**Comment by dgjinsu** [comment]
저도 없는 게 더 좋을 것 같습니다

**Comment by CountryBird** [comment]
의견 반영했습니다. 좋은 의견 감사합니다.

**Comment by choibumku00** [comment]
그게 좋을것 같습니다. 위키도 한번 수정할 계획이었는데
모든 사용자가 수정할 수 있기에 다같이 추가하고 수정해 나가면 좋을것 같습니다.
