### ISSUE TITLE
Issues에 지식그래프에 대해 정리했던 내용을 Wiki에 추가했습니다.

### ISSUE THREAD

**Issue by VeaNae1** [chunsejin/web-media-mix#82]
Wiki에 대해 공부하면서 제가 적었던 지식그래프에 대한 정리가 Issues보다는 Wiki에 있는 것이 맞다고 생각하여 추가하였습니다.

**Comment by MinkwanK** [comment]
고생하셨습니다.

**Comment by Fromis999** [comment]
감사합니다.

**Comment by sj2305** [comment]
좋습니다.

**Comment by lsm2000** [comment]
지식그래프의 주요특성을 토글기능을 사용하면  보기 좋아보여서 추가해봤습니다.

**Comment by VeaNae1** [comment]
> 지식그래프의 주요특성을 토글기능을 사용하면 보기 좋아보여서 추가해봤습니다.

확실히 한눈에 보기 깔끔해지네요! 좋은 수정 감사합니다.

**Comment by KMJ-KimMinJu** [comment]
감사합니다. 더욱 깔끔해졌네요.

**Comment by dgjinsu** [comment]
감사합니다
