### ISSUE TITLE
read me 문체 수정 

### ISSUE THREAD

**Issue by pshpjr** [chunsejin/web-media-mix#84]
지금 readme의 경우

"요구한다."

"구성하고자 함."

"시작되었습니다."

등 어미가 통일되지 않은 상태이기에 이를 수정하려고 합니다. 

또한, 여러 명이 동시에 readme를 변경할 경우 conflict가 발생할 확률이 높으니

readme만 수정하는 modify_readme 브랜치를 만들어 여기서만 readme를 변경하면 좋겠습니다. 

3명 이상 동의하시면 진행하겠습니다.

**Comment by SeokJinB** [comment]
동의합니다. 일관되지 않은 어미형식은 불편함을 가져다 줄 수도 있다고 생각합니다.

**Comment by MinkwanK** [comment]
동의합니다. conflict가 자주 발생해서 해결방안이 필요했습니다

**Comment by choibumku00** [comment]
저도 동의 합니다
