### ISSUE TITLE
Wiki의 '유형' 내용 추가

### ISSUE THREAD

**Issue by CountryBird** [chunsejin/web-media-mix#86]
Wiki의 '유형' 부분에 조금의 설명과, 참고용 사진들을 첨부하였습니다.
더 추가할 사항 있거나, 문제가 있을 시 편집해 주시면 감사하겠습니다.

**Comment by VeaNae1** [comment]
수고하셨습니다! 예시가 추가되어 눈에 더 쉽게 들어오는 것 같습니다.
