### ISSUE TITLE
Github Projects 기능을 사용하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by dgjinsu** [chunsejin/web-media-mix#87]
> To Do : 해야 할 작업
> In Progress : 진행 중인 작업 
> Done : 완료된 작업

위와 같은 기능들을 사용하면 새로 추가 된 이슈, 진행중인 작업, Merge 되거나 close 된 이슈를 한눈에 볼 수 있습니다. 

따라서 프로젝트의 진행상황을 한번에 파악하기 좋을 것 같습니다.

**Comment by Fromis999** [comment]
사용법을 아직 잘 몰라서 공부하면서 사용해보면 될 것 같습니다
