### ISSUE TITLE
arrows를 잘못 만든것 같습니다

### ISSUE THREAD

**Issue by choibumku00** [chunsejin/web-media-mix#93]
현재 arrows를 만들때 값은 안넣고 카테고리만 만들어놨습니다.
그리고 저희가 만들때 카테고리를 caption에 적으며 만들어왔습니다.

그런데 caption이 값이고, labels가 카테고리인것 같습니다.

예를 들어 스폰지밥(등장인물)이 있으면 스폰지밥이 caption이고, 등장인물이 labels인것 같습니다.

아직 정확한건 아니라서 좀 더 찾아봐야겠지만 혹시 아시는분이나 의견 남겨주시면 감사합니다

labels가 카테고리가 맞으면 전부 수정하도록 하겠습니다.

**Comment by lsm2000** [comment]
저도 labels이 카테고리가 맞는거 같습니다

**Comment by MinkwanK** [comment]
https://medium.com/neo4j/drawing-graphs-with-arrows-app-ee5735caa04d
 
이 글을 보니 노드들을 하나의 집합으로 묶어주는게 label 이라고 하네오ㆍ

**Comment by choibumku00** [comment]
> https://medium.com/neo4j/drawing-graphs-with-arrows-app-ee5735caa04d
> 
> 이 글을 보니 노드들을 하나의 집합으로 묶어주는게 label 이라고 하네요

그럼 고치는게 맞겠죠??

**Comment by MinkwanK** [comment]
![Screenshot_20220412-182618_YouTube.jpg](https://user-images.githubusercontent.com/94276637/162928132-46e5eb27-4af1-4058-8020-c2ed5e759ac7.jpg) 

저도 잘 모르겠네요
이 사진을 보니 수정이 필요한지 모르겠습니다.
matrix 영화에 movie 라벨이 달리고 배우 이름에 actor라벨과 perosn 라벨이 달립니다.

저희가 작성하는 미디어의 제목이나
등장인물들에게는 라벨을 넣어주는게 맞는 것 같습니다. 등장인물들을 하나로 묶어주고 웹툰의 제목에 웹툰 라벨을 붙여 이게 웹툰이라는걸 보여주니까요.

그런데 '웹툰' 노드에 webtoon 라벨을 달면 웹툰 노드가 webtoon라벨에 속하게 되니 제가 보기엔 어색해보입니다. 라벨이란건 노드들을 하나로 묶어주는 역할인데 상위 범주인 웹툰 노드가  그 라벨안에 들어가면 안되는 것 같습니다.

**Comment by MinkwanK** [comment]
기본 틀은 실제 미디어를 넣었을때 표시할 라벨이라 생각하고 진행하면 되지 않나요?

**Comment by choibumku00** [comment]
제가 제대로 이해했는지는 모르겠지만 
지금 노드 caption에 웹툰이라고 적은 부분을
caption값은 비우고 label에 웹툰이라고 적는게 어떨까요
caption에는 웹툰처럼 분류 기준을 적는게 아니라 실제 값이 들어 가야한다고 생각합니다

label이 분류 기준인듯해서 현재 저희가 한 모든 값은 label로 옮기고, 추후 이 노드에 값(예:스폰지밥)을 넣는다면 caption에 바로 넣을수 있게 준비해두는게 나을것 같습니다

그냥 나두는것이 나을듯하면 나두겠습니다

**Comment by MinkwanK** [comment]
**label이 분류 기준인듯해서 현재 저희가 한 모든 값은 label로 옮기고, 추후 이 노드에 값(예:스폰지밥)을 넣는다면 caption에 바로 넣을수 있게 준비해두는게 나을것 같습니다**

-> 이 말씀 이해했습니다. 생각해보니 label로 미리 옮기고 작업하면 더 편하겠네요. 
저도 웹툰->영화화 다시 변경하겠습니다.

**Comment by choibumku00** [comment]
네 감사합니다!! 다른것들도 다 수정하도록 하겠습니다.
